services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
    expose:
      - 3306
    restart: unless-stopped
    command: --authentication_policy=mysql_native_password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - /home/user/database:/var/lib/mysql
    networks:
      - internalnet

  server:
    container_name: server 
    image: nodeapp:vl
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'letmein'
      DB_NAME: exampledb
      DB_CONNECTION_LIMIT: 20
    build: .
    expose:
      - 3001
    volumes:
      - /home/user/nodeapp:/code
    depends_on:
      - db
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge